version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: shortener_pass
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - shortener_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Novo serviço de Cache
  redis:
    image: redis:7-alpine
    container_name: shortener_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  shortener_pg_data:
