version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: shortener_pass
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - shortener_pg_data:/var/lib/postgresql/data
      # Mapeia o arquivo SQL para rodar automaticamente na primeira vez que o banco subir
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  shortener_pg_data: